name: Save Data to CSV

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  save-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create data.csv
      run: |
        echo "date,category,amount" > data.csv
        # Tambahkan data CSV yang Anda inginkan di sini
        echo "2023-07-15,food,10000" >> data.csv

    - name: Commit and push CSV
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add data.csv
        git commit -m "Update data.csv"
        git push
